In [127]:
import pandas as pd
import numpy as np
from km import KMeans
from SVD import Matrix
from kmode import KModes
import matplotlib.pyplot as plt
import math

In [128]:
def load_data(file_path):
    return pd.read_csv(file_path)


In [133]:
def elbow_method(data, max_clusters=4):
    distortions = []
    for i in range(1, max_clusters + 1):
        km = KModes(i)
        # print(data.shape)
        km.fit(data)
        distortions.append(km.get_cost(data))
    # Plotting the elbow curve
    plt.plot(range(1, max_clusters + 1), distortions, marker='o')
    plt.xlabel('Number of clusters')
    plt.ylabel('Distortion')
    plt.title('Elbow Method')
    plt.show()


In [134]:
file_path = "./EncodedCombined2.csv"  # Replace with your dataset file path
data = load_data(file_path)

avg_rating = load_data("./Movie_Rating.csv")
# Assuming the data matrix is constructed with users as rows and movies as columns
data_matrix = data.iloc[:601,:]  # Exclude first column (user IDs)
# data_matrix.drop(columns=["Zip-code","Title"],inplace=True)
print(data_matrix)


        UserID  MovieID  Rating  Action  Adventure  Animation  Children's  \
0            1     1193       5       0          0          0           0   
1            1      661       3       0          0          1           1   
2            1      914       3       0          0          0           0   
3            1     3408       4       0          0          0           0   
4            1     2355       5       0          0          1           1   
...        ...      ...     ...     ...        ...        ...         ...   
869365    4211     3791       2       0          0          0           0   
869366    4211     3806       3       0          0          0           0   
869367    4211     3840       4       0          0          0           0   
869368    4211     3766       2       1          0          0           0   
869369    4211     3834       2       0          1          0           0   

        Comedy  Crime  Documentary  ...  Musical  Mystery  Romance  Sci-Fi 

In [135]:
data_matrix["MovieID"]=data_matrix["MovieID"].astype(np.int16)
data_matrix["UserID"]=data_matrix["UserID"].astype(np.int16)
for col in data_matrix.columns:
    if(col!="MovieID" and col!="UserID"):
        data_matrix[col]=data_matrix[col].astype(np.int8)
print(data_matrix.dtypes)

UserID         int16
MovieID        int16
Rating          int8
Action          int8
Adventure       int8
Animation       int8
Children's      int8
Comedy          int8
Crime           int8
Documentary     int8
Drama           int8
Fantasy         int8
Film-Noir       int8
Horror          int8
Musical         int8
Mystery         int8
Romance         int8
Sci-Fi          int8
Thriller        int8
War             int8
Western         int8
Gender          int8
Age             int8
Occupation      int8
dtype: object


In [136]:
# print(data_matrix)
data_mat=data_matrix.values
elbow_method(data_mat)

Cost i.e., sum of delta metrics for all data-points for Iteration 1:  6196325
Cost i.e., sum of delta metrics for all data-points for Iteration 2:  5615832
Cost i.e., sum of delta metrics for all data-points for Iteration 1:  5763123
Cost i.e., sum of delta metrics for all data-points for Iteration 2:  5462999
Cost i.e., sum of delta metrics for all data-points for Iteration 1:  5952987
Cost i.e., sum of delta metrics for all data-points for Iteration 2:  5258445
Cost i.e., sum of delta metrics for all data-points for Iteration 3:  5163185
Cost i.e., sum of delta metrics for all data-points for Iteration 1:  5492451
Cost i.e., sum of delta metrics for all data-points for Iteration 2:  5085538
Cost i.e., sum of delta metrics for all data-points for Iteration 1:  5564161
Cost i.e., sum of delta metrics for all data-points for Iteration 2:  4953154
Cost i.e., sum of delta metrics for all data-points for Iteration 3:  4835669
Cost i.e., sum of delta metrics for all data-points for Iteratio

KeyboardInterrupt: 

In [ ]:
k=4
km = KModes(k)
km.fit(data_mat)
km.cluster_centroids

Cost i.e., sum of delta metrics for all data-points for Iteration 1:  3247
Cost i.e., sum of delta metrics for all data-points for Iteration 2:  3000
Cost i.e., sum of delta metrics for all data-points for Iteration 3:  2940


[[15, 457, 4, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 25, 7],
 [12,
  2002,
  3,
  0,
  0,
  0,
  0,
  0,
  1,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  25,
  12],
 [2, 260, 3, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 56, 16],
 [15, 1193, 4, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 25, 7]]

In [ ]:
clustered_ratings=km.predict(data_mat)
clustered_ratings

[(array([   1, 1193,    5,    0,    0,    0,    0,    0,    0,    0,    1,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    1,
            1,   10], dtype=int16),
  3),
 (array([  1, 661,   3,   0,   0,   1,   1,   0,   0,   0,   0,   0,   0,
           0,   1,   0,   0,   0,   0,   0,   0,   1,   1,  10], dtype=int16),
  1),
 (array([  1, 914,   3,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
           0,   1,   0,   1,   0,   0,   0,   0,   1,   1,  10], dtype=int16),
  1),
 (array([   1, 3408,    4,    0,    0,    0,    0,    0,    0,    0,    1,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    1,
            1,   10], dtype=int16),
  3),
 (array([   1, 2355,    5,    0,    0,    1,    1,    1,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    1,
            1,   10], dtype=int16),
  1),
 (array([   1, 1197,    3,    1,    1,    0,    0,    1,    0,    0,    0,
            0,    0,    0,    0

In [ ]:
rows_per_clusters=[]
for cluster in range(k):
    rows_per_clusters.append([])

for row in clustered_ratings:
    row_cluster=row[1]
    rows_per_clusters[row_cluster].append(row[0])

rows_per_clusters

[[array([  1, 745,   3,   0,   0,   1,   0,   1,   0,   0,   0,   0,   0,
           0,   0,   0,   0,   0,   1,   0,   0,   1,   1,  10], dtype=int16),
  array([   1, 2762,    4,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    1,    0,    0,    1,
            1,   10], dtype=int16),
  array([   1, 2692,    4,    1,    0,    0,    0,    0,    1,    0,    0,
            0,    0,    0,    0,    0,    1,    0,    0,    0,    0,    1,
            1,   10], dtype=int16),
  array([   2, 2353,    4,    1,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    1,    0,    0,    0,
           56,   16], dtype=int16),
  array([  2, 736,   4,   1,   1,   0,   0,   0,   0,   0,   0,   0,   0,
           0,   0,   0,   1,   0,   1,   0,   0,   0,  56,  16], dtype=int16),
  array([   2, 1953,    4,    1,    0,    0,    0,    0,    1,    0,    1,
            0,    0,    0,    0,    0,    0,    0,    1,    0

SVD

In [ ]:
user_ids = set(data_matrix['UserID'])
user_ids

{1, 2, 12, 15, 17}

In [ ]:
def get_non_zero_eigenvalues(Sigma):
    # Extract diagonal elements of Sigma
    diagonal_elements = np.diag(Sigma)

    # Filter out values not close to zero
    non_zero_eigenvalues = [eigenvalue for eigenvalue in diagonal_elements if not math.isclose(eigenvalue, 0)]

    return non_zero_eigenvalues


In [ ]:
new_user_cluster=2
avgdict = avg_rating.set_index('MovieID')['AvgRating'].to_dict() ## might need to change this
avg_dict = {int(key): float(value)  for key, value in avgdict.items() if value != 'Avg. Rating'}

ratings_A = rows_per_clusters[new_user_cluster]
column_names = [
    "UserID", "MovieID", "Rating", "Action", "Adventure", "Animation", 
    "Children's", "Comedy", "Crime", "Documentary", "Drama", "Fantasy", 
    "Film-Noir", "Horror", "Musical", "Mystery", "Romance", "Sci-Fi", 
    "Thriller", "War", "Western", "Gender", "Age", "Occupation"
]
ratings_df=pd.DataFrame(ratings_A,columns=column_names)

A=ratings_df.pivot(index='UserID', columns='MovieID', values='Rating')
A_mat = pd.DataFrame(A)
A_watched=A_mat.copy()
A_mat= A_mat.fillna(avg_dict)
A

MovieID  21    24    95    110   165   198   235   260   292   316   ...  \
UserID                                                               ...   
1         NaN   NaN   NaN   NaN   NaN   NaN   NaN   4.0   NaN   NaN  ...   
2         1.0   NaN   2.0   5.0   3.0   NaN   3.0   NaN   3.0   NaN  ...   
17        NaN   3.0   NaN   NaN   NaN   4.0   NaN   5.0   NaN   4.0  ...   

MovieID  3702  3703  3704  3745  3793  3809  3827  3863  3893  3932  
UserID                                                               
1         NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN  
2         NaN   NaN   NaN   NaN   NaN   3.0   NaN   NaN   1.0   NaN  
17        3.0   5.0   4.0   4.0   4.0   NaN   4.0   3.0   NaN   3.0  

[3 rows x 167 columns]

In [ ]:
A_mat=A_mat.round(2)
# print(A_mat.dtypes)
A_mat,A_watched

(MovieID  21    24    95    110   165   198   235   260   292   316   ...  \
 UserID                                                               ...   
 1        3.62  3.18  2.88  4.23  3.56   3.3   3.7  4.00  3.27  3.49  ...   
 2        1.00  3.18  2.00  5.00  3.00   3.3   3.0  4.45  3.00  3.49  ...   
 17       3.62  3.00  2.88  4.23  3.56   4.0   3.7  5.00  3.27  4.00  ...   
 
 MovieID  3702  3703  3704  3745  3793  3809  3827  3863  3893  3932  
 UserID                                                               
 1        3.66  3.67  3.17  3.38  3.82   3.4  3.38  3.26   3.5  3.75  
 2        3.66  3.67  3.17  3.38  3.82   3.0  3.38  3.26   1.0  3.75  
 17       3.00  5.00  4.00  4.00  4.00   3.4  4.00  3.00   3.5  3.00  
 
 [3 rows x 167 columns],
 MovieID  21    24    95    110   165   198   235   260   292   316   ...  \
 UserID                                                               ...   
 1         NaN   NaN   NaN   NaN   NaN   NaN   NaN   4.0   NaN   NaN  ...   


In [ ]:
A = Matrix(A_mat)
U,Sigma,V = A.svd()

non_zero_diag = get_non_zero_eigenvalues(Sigma)
U_red,Sigma_red,V_red = A.reduced_svd(int(non_zero_diag[0]))  # Number of components for SVD 


Outputs

[[ 0.56479585 -0.2335902  -0.79148042]
 [ 0.56653494  0.80713067  0.16606699]
 [ 0.60003651 -0.54219526  0.58820107]]
[[83.3216743   0.          0.          0.          0.          0.
   0.          0.          0.          0.          0.          0.
   0.          0.          0.          0.          0.          0.
   0.          0.          0.          0.          0.          0.
   0.          0.          0.          0.          0.          0.
   0.          0.          0.          0.          0.          0.
   0.          0.          0.          0.          0.          0.
   0.          0.          0.          0.          0.          0.
   0.          0.          0.          0.          0.          0.
   0.          0.          0.          0.          0.          0.
   0.          0.          0.          0.          0.          0.
   0.          0.          0.          0.          0.          0.
   0.          0.          0.          0.          0.          0.
   0.         

In [ ]:
# new_mat = (U_red.dot(Sigma)).dot(V_red)
new_mat = np.matmul(U_red,np.matmul(Sigma_red,np.transpose(V_red)))
new_mat

array([[-3.62, -3.18, -2.88, -4.23, -3.56, -3.3 , -3.7 , -4.  , -3.27,
        -3.49, -4.55, -3.38, -4.09, -3.52, -3.63, -3.08, -2.99, -2.83,
        -3.76, -2.74, -3.92, -4.27, -4.06, -3.92, -4.35, -3.55, -3.55,
        -3.43, -4.09, -4.45, -3.51, -3.91, -4.  , -3.67, -3.7 , -3.98,
        -4.09, -3.97, -3.92, -3.74, -3.95, -4.29, -3.  , -4.48, -4.08,
        -4.02, -3.8 , -4.27, -4.25, -4.08, -4.01, -4.01, -4.25, -4.14,
        -4.1 , -3.95, -5.  , -4.14, -3.71, -3.81, -3.54, -3.41, -3.88,
        -3.66, -3.27, -3.81, -3.64, -4.14, -3.04, -3.27, -3.74, -3.41,
        -4.05, -3.08, -2.96, -3.95, -3.17, -3.04, -3.19, -3.94, -3.8 ,
        -3.88, -3.88, -3.25, -3.56, -3.52, -4.08, -3.34, -3.36, -4.34,
        -3.47, -4.07, -2.85, -3.36, -2.75, -3.65, -3.56, -4.01, -3.61,
        -3.53, -3.42, -3.83, -3.7 , -3.31, -3.88, -2.95, -4.13, -3.54,
        -3.4 , -3.51, -4.14, -2.37, -3.47, -3.71, -3.18, -4.32, -3.26,
        -3.41, -3.54, -3.29, -3.9 , -3.36, -3.86, -3.08, -3.91, -2.62,
      

In [ ]:
def invert_array(arr):
    for i in range(len(arr)):
        for j in range(len(arr[i])):
            arr[i][j] *= -1
    return arr

corrected_array=invert_array(new_mat)
corrected_array

array([[3.62, 3.18, 2.88, 4.23, 3.56, 3.3 , 3.7 , 4.  , 3.27, 3.49, 4.55,
        3.38, 4.09, 3.52, 3.63, 3.08, 2.99, 2.83, 3.76, 2.74, 3.92, 4.27,
        4.06, 3.92, 4.35, 3.55, 3.55, 3.43, 4.09, 4.45, 3.51, 3.91, 4.  ,
        3.67, 3.7 , 3.98, 4.09, 3.97, 3.92, 3.74, 3.95, 4.29, 3.  , 4.48,
        4.08, 4.02, 3.8 , 4.27, 4.25, 4.08, 4.01, 4.01, 4.25, 4.14, 4.1 ,
        3.95, 5.  , 4.14, 3.71, 3.81, 3.54, 3.41, 3.88, 3.66, 3.27, 3.81,
        3.64, 4.14, 3.04, 3.27, 3.74, 3.41, 4.05, 3.08, 2.96, 3.95, 3.17,
        3.04, 3.19, 3.94, 3.8 , 3.88, 3.88, 3.25, 3.56, 3.52, 4.08, 3.34,
        3.36, 4.34, 3.47, 4.07, 2.85, 3.36, 2.75, 3.65, 3.56, 4.01, 3.61,
        3.53, 3.42, 3.83, 3.7 , 3.31, 3.88, 2.95, 4.13, 3.54, 3.4 , 3.51,
        4.14, 2.37, 3.47, 3.71, 3.18, 4.32, 3.26, 3.41, 3.54, 3.29, 3.9 ,
        3.36, 3.86, 3.08, 3.91, 2.62, 2.53, 2.91, 4.02, 3.74, 3.2 , 3.2 ,
        3.68, 3.54, 3.28, 3.39, 3.44, 3.63, 4.15, 3.77, 3.75, 2.86, 3.2 ,
        3.3 , 3.34, 3.59, 3.68, 4.24, 

In [ ]:
movie_averages=np.mean(corrected_array,axis=0)
movie_IDs=A_watched.columns
movie_avg_df=pd.DataFrame(movie_averages,index=movie_IDs)
movie_avg_df

0
MovieID          
21       2.746667
24       3.120000
95       2.586667
110      4.486667
165      3.373333
...           ...
3809     3.266667
3827     3.586667
3863     3.173333
3893     2.666667
3932     3.500000

[167 rows x 1 columns]

In [ ]:
# Recommend movies for a particular user
def recommend_movies(user_id, users_watched,movie_averages):      
    df=users_watched[users_watched.index==user_id]
    userMovies=[]
    for index, row in df.iterrows():
        for column in df.columns:
            value = row[column]
            # Check if the value is not NaN (not null)
            if not pd.isna(value):
                userMovies.append(column)

    filtered_df = movie_averages[~movie_averages.index.isin(userMovies)]
    filtered_df=filtered_df.reset_index()
    
    movies=pd.read_csv("movies.csv")
    movies=movies.set_index(keys=['MovieID'])
    merged_df=pd.merge(movies,filtered_df,on='MovieID')
    merged_df=merged_df.sort_values(by=0,ascending=False)
    recommendations=merged_df.to_numpy()
    # print(recommendations)
    return recommendations

In [ ]:
# Recommend movies for the user
user_id=1
recommended_movies = recommend_movies(user_id,A_watched,movie_avg_df)
print("Recommended movies for User ", user_id)
for movie in recommended_movies[:5]:  # Display top 10 recommended movies
    print(f"Title : {movie[1]} , MovieID : {movie[0]} , Rating : {movie[3]} , Genres : {movie[2]}")  # Assuming the first column is movie titles


Recommended movies for User  1
Title : Star Wars: Episode V - The Empire Strikes Back (1980) , MovieID : 1196 , Rating : 4.76333333333334 , Genres : Action|Adventure|Drama|Sci-Fi|War
Title : Shawshank Redemption, The (1994) , MovieID : 318 , Rating : 4.699999999999999 , Genres : Drama
Title : Dr. Strangelove or: How I Learned to Stop Worrying and Love the Bomb (1963) , MovieID : 750 , Rating : 4.6333333333333355 , Genres : Sci-Fi|War
Title : Silence of the Lambs, The (1991) , MovieID : 593 , Rating : 4.566666666666666 , Genres : Drama|Thriller
Title : Blade Runner (1982) , MovieID : 541 , Rating : 4.51333333333334 , Genres : Film-Noir|Sci-Fi
