In [23]:
import pandas as pd
import numpy as np
from km import KMeans
from SVD import Matrix
from kmode import KModes
import matplotlib.pyplot as plt
import math

In [24]:
def load_data(file_path):
    return pd.read_csv(file_path)


In [25]:
def elbow_method(data, max_clusters=50):
    distortions = []
    for i in range(1, max_clusters + 1):
        km = KModes(i)
        # print(data.shape)
        km.fit(data)
        distortions.append(km.get_cost(data))
    # Plotting the elbow curve
    plt.plot(range(1, max_clusters + 1), distortions, marker='o')
    plt.xlabel('Number of clusters')
    plt.ylabel('Distortion')
    plt.title('Elbow Method')
    plt.show()


In [26]:
file_path = "./EncodedCombined2.csv"  # Replace with your dataset file path
data = load_data(file_path)

avg_rating = load_data("./Genre_Rating.csv")
# Assuming the data matrix is constructed with users as rows and movies as columns
data_matrix = data.iloc[:10000,:]  # Exclude first column (user IDs)
# data_matrix.drop(columns=["Zip-code","Title"],inplace=True)
print(data_matrix)


      UserID  MovieID  Rating  Action  Adventure  Animation  Children's  \
0          1     1193       5       0          0          0           0   
1          1      661       3       0          0          1           1   
2          1      914       3       0          0          0           0   
3          1     3408       4       0          0          0           0   
4          1     2355       5       0          0          1           1   
...      ...      ...     ...     ...        ...        ...         ...   
9995     195     2012       3       0          0          0           0   
9996     195     1214       5       1          0          0           0   
9997     195     1215       4       1          1          0           0   
9998     195      541       5       0          0          0           0   
9999     195      542       2       0          0          0           0   

      Comedy  Crime  Documentary  ...  Musical  Mystery  Romance  Sci-Fi  \
0          0      0    

In [27]:
data_matrix["MovieID"]=data_matrix["MovieID"].astype(np.int16)
data_matrix["UserID"]=data_matrix["UserID"].astype(np.int16)
for col in data_matrix.columns:
    if(col!="MovieID" and col!="UserID"):
        data_matrix[col]=data_matrix[col].astype(np.int8)
print(data_matrix.dtypes)

# print(data_matrix)

UserID         int16
MovieID        int16
Rating          int8
Action          int8
Adventure       int8
Animation       int8
Children's      int8
Comedy          int8
Crime           int8
Documentary     int8
Drama           int8
Fantasy         int8
Film-Noir       int8
Horror          int8
Musical         int8
Mystery         int8
Romance         int8
Sci-Fi          int8
Thriller        int8
War             int8
Western         int8
Gender          int8
Age             int8
Occupation      int8
dtype: object


In [28]:
# print(data_matrix)
data_mat=data_matrix.values
elbow_method(data_mat)

Cost i.e., sum of delta metrics for all data-points for Iteration 1:  81079
Cost i.e., sum of delta metrics for all data-points for Iteration 2:  64467
Cost i.e., sum of delta metrics for all data-points for Iteration 1:  66660
Cost i.e., sum of delta metrics for all data-points for Iteration 2:  61407
Cost i.e., sum of delta metrics for all data-points for Iteration 1:  69446
Cost i.e., sum of delta metrics for all data-points for Iteration 2:  58383
Cost i.e., sum of delta metrics for all data-points for Iteration 1:  64962
Cost i.e., sum of delta metrics for all data-points for Iteration 2:  57987
Cost i.e., sum of delta metrics for all data-points for Iteration 1:  59040
Cost i.e., sum of delta metrics for all data-points for Iteration 2:  53098
Cost i.e., sum of delta metrics for all data-points for Iteration 1:  60569
Cost i.e., sum of delta metrics for all data-points for Iteration 2:  52885
Cost i.e., sum of delta metrics for all data-points for Iteration 3:  52501
Cost i.e., s

In [ ]:
data_mat = data_mat.astype(float)
data_mat 

array([[1.000e+00, 1.193e+03, 5.000e+00, ..., 1.000e+00, 1.000e+00,
        1.000e+01],
       [1.000e+00, 6.610e+02, 3.000e+00, ..., 1.000e+00, 1.000e+00,
        1.000e+01],
       [1.000e+00, 9.140e+02, 3.000e+00, ..., 1.000e+00, 1.000e+00,
        1.000e+01],
       ...,
       [1.800e+01, 9.190e+02, 5.000e+00, ..., 1.000e+00, 1.800e+01,
        3.000e+00],
       [1.800e+01, 5.950e+02, 5.000e+00, ..., 1.000e+00, 1.800e+01,
        3.000e+00],
       [1.800e+01, 2.018e+03, 4.000e+00, ..., 1.000e+00, 1.800e+01,
        3.000e+00]])

In [ ]:
k=45
km = KModes(k)
km.fit(data_mat)
km.cluster_centroids

Cost i.e., sum of delta metrics for all data-points for Iteration 1:  1493
Cost i.e., sum of delta metrics for all data-points for Iteration 2:  1382


[[15, 1370, 3, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 25, 7],
 [15, 2396, 4, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 25, 7],
 [15, 260, 4, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 25, 7],
 [17, 260, 3, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 50, 1],
 [17, 50, 5, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 50, 1],
 [17, 110, 4, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 50, 1],
 [15, 73, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 25, 7],
 [15, 160, 2, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 25, 7],
 [15, 296, 3, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 25, 7],
 [2, 1408, 3, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 56, 16],
 [1, 2355, 4, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 10],
 [2, 21, 5, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 56, 16],
 [1, 2018, 4, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,

In [ ]:
clustered_ratings=km.predict(data_mat)
clustered_ratings

[(array([1.000e+00, 1.193e+03, 5.000e+00, 0.000e+00, 0.000e+00, 0.000e+00,
         0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 1.000e+00, 0.000e+00,
         0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00,
         0.000e+00, 0.000e+00, 0.000e+00, 1.000e+00, 1.000e+00, 1.000e+01]),
  14),
 (array([  1., 661.,   3.,   0.,   0.,   1.,   1.,   0.,   0.,   0.,   0.,
           0.,   0.,   0.,   1.,   0.,   0.,   0.,   0.,   0.,   0.,   1.,
           1.,  10.]),
  18),
 (array([  1., 914.,   3.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
           0.,   0.,   0.,   1.,   0.,   1.,   0.,   0.,   0.,   0.,   1.,
           1.,  10.]),
  38),
 (array([1.000e+00, 3.408e+03, 4.000e+00, 0.000e+00, 0.000e+00, 0.000e+00,
         0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 1.000e+00, 0.000e+00,
         0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00,
         0.000e+00, 0.000e+00, 0.000e+00, 1.000e+00, 1.000e+00, 1.000e+01]),
  14),
 (array([1.000e+00, 2.

In [ ]:
rows_per_clusters=[]
for cluster in range(k):
    rows_per_clusters.append([])

for row in clustered_ratings:
    row_cluster=row[1]
    rows_per_clusters[row_cluster].append(row[0])

rows_per_clusters

[[array([2.000e+00, 1.792e+03, 3.000e+00, 1.000e+00, 0.000e+00, 0.000e+00,
         0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00,
         0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00,
         1.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 5.600e+01, 1.600e+01]),
  array([2.000e+00, 1.687e+03, 3.000e+00, 1.000e+00, 0.000e+00, 0.000e+00,
         0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00,
         0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00,
         1.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 5.600e+01, 1.600e+01]),
  array([2.000e+00, 2.881e+03, 3.000e+00, 1.000e+00, 0.000e+00, 0.000e+00,
         0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00,
         0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00,
         1.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 5.600e+01, 1.600e+01]),
  array([2.000e+00, 2.126e+03, 3.000e+00, 1.000e+00, 0.000e+00, 0.000e+00,
         0.000e+00,

SVD

In [ ]:
user_ids = set(data_matrix['UserID'])
user_ids

{1, 2, 15, 17, 18}

In [ ]:
def get_non_zero_eigenvalues(Sigma):
    # Extract diagonal elements of Sigma
    diagonal_elements = np.diag(Sigma)

    # Filter out values not close to zero
    non_zero_eigenvalues = [eigenvalue for eigenvalue in diagonal_elements if not math.isclose(eigenvalue, 0)]

    return non_zero_eigenvalues


In [ ]:
new_user_cluster=2
avgdict = avg_rating.set_index('Genre')['Avg. Rating'].to_dict() ## might need to change this
avg_dict = {key: float(value)  for key, value in avgdict.items() if value != 'Avg. Rating'}

ratings_A = rows_per_clusters[new_user_cluster]
column_names = [
    "UserID", "MovieID", "Rating", "Action", "Adventure", "Animation", 
    "Children's", "Comedy", "Crime", "Documentary", "Drama", "Fantasy", 
    "Film-Noir", "Horror", "Musical", "Mystery", "Romance", "Sci-Fi", 
    "Thriller", "War", "Western", "Gender", "Age", "Occupation"
]
ratings_df=pd.DataFrame(ratings_A,columns=column_names)

A=ratings_df.pivot(index='UserID', columns='MovieID', values='Rating')
A_mat = pd.DataFrame(A)
A_watched=A_mat.copy()
A_mat= A_mat.fillna(avg_dict)
A

MovieID  260.0   653.0   3489.0
UserID                         
15.0        4.0     2.0     4.0

In [ ]:
A_mat=A_mat.round(2)
# print(A_mat.dtypes)
A_mat,A_watched

(MovieID  260.0   653.0   3489.0
 UserID                         
 15.0        4.0     2.0     4.0,
 MovieID  260.0   653.0   3489.0
 UserID                         
 15.0        4.0     2.0     4.0)

In [ ]:
A = Matrix(A_mat)
U,Sigma,V = A.svd()

non_zero_diag = get_non_zero_eigenvalues(Sigma)
U_red,Sigma_red,V_red = A.reduced_svd(int(non_zero_diag[0]))  # Number of components for SVD 


Outputs

[[0.96862816]]
[[6. 0. 0.]]
[[6.45752106e-01 9.08866648e-07 4.66450783e-07]
 [3.22876053e-01 4.54433324e-07 2.33225391e-07]
 [6.45752106e-01 9.08866648e-07 4.66450783e-07]]

Outputs

[[0.96862816]]
[[6. 0. 0.]]
[[6.45752106e-01 9.08866648e-07 4.66450783e-07]
 [3.22876053e-01 4.54433324e-07 2.33225391e-07]
 [6.45752106e-01 9.08866648e-07 4.66450783e-07]]


In [ ]:
# new_mat = (U_red.dot(Sigma)).dot(V_red)
new_mat = np.matmul(U_red,np.matmul(Sigma_red,np.transpose(V_red)))
new_mat

array([[3.75296204, 1.87648102, 3.75296204]])

In [ ]:
def invert_array(arr):
    for i in range(len(arr)):
        for j in range(len(arr[i])):
            arr[i][j] *= -1
    return arr

corrected_array=invert_array(new_mat)
corrected_array

array([[-3.75296204, -1.87648102, -3.75296204]])

In [ ]:
movie_averages=np.mean(corrected_array,axis=0)
movie_IDs=A_watched.columns
movie_avg_df=pd.DataFrame(movie_averages,index=movie_IDs)
movie_avg_df

0
MovieID          
260.0   -3.752962
653.0   -1.876481
3489.0  -3.752962

In [ ]:
# Recommend movies for a particular user
def recommend_movies(user_id, users_watched,movie_averages):      
    df=users_watched[users_watched.index==user_id]
    userMovies=[]
    for index, row in df.iterrows():
        for column in df.columns:
            value = row[column]
            # Check if the value is not NaN (not null)
            if not pd.isna(value):
                userMovies.append(column)

    filtered_df = movie_averages[~movie_averages.index.isin(userMovies)]
    filtered_df=filtered_df.reset_index()
    
    movies=pd.read_csv("movies.csv")
    movies=movies.set_index(keys=['MovieID'])
    merged_df=pd.merge(movies,filtered_df,on='MovieID')
    merged_df=merged_df.sort_values(by=0,ascending=False)
    recommendations=merged_df.to_numpy()
    # print(recommendations)
    return recommendations

In [ ]:
# Recommend movies for the user
user_id=1
recommended_movies = recommend_movies(user_id,A_watched,movie_avg_df)
print("Recommended movies for User ", user_id)
for movie in recommended_movies[:5]:  # Display top 10 recommended movies
    print(f"Title : {movie[1]} , MovieID : {movie[0]} , Rating : {movie[3]} , Genres : {movie[2]}")  # Assuming the first column is movie titles


Recommended movies for User  1
Title : Dragonheart (1996) , MovieID : 653 , Rating : -1.8764810190332701 , Genres : Action|Adventure|Fantasy
Title : Star Wars: Episode IV - A New Hope (1977) , MovieID : 260 , Rating : -3.7529620380665403 , Genres : Action|Adventure|Fantasy|Sci-Fi
Title : Hook (1991) , MovieID : 3489 , Rating : -3.7529620380665403 , Genres : Adventure|Fantasy
