In [101]:
import numpy as np
import math

In [102]:
class Matrix:
    def __init__(self, A):
        self.A = A

    def QRDecompose(self, A, standard=False):
        
        m, n = A.shape  
        Q = np.zeros((m, n))
        R = np.zeros((n, n))

        for j in range(n):
            v = A[:, j]
            for i in range(j):
                R[i, j] = np.dot(Q[:, i], A[:, j])
                v -= R[i, j] * Q[:, i]
            R[j, j] = np.linalg.norm(v)
            Q[:, j] = v / R[j, j]

        if standard:
            for i in range(n):
                if R[i, i] < 0.0:
                    Q[:, i] *= -1
                    R[i, :] *= -1

        return Q, R
    
    def is_upper_tri(self, A, tol):
        n = len(A)
        for i in range(0,n):
            for j in range(0,i):
            # if the lower triangular entries fall below a threshold (tol), only then it is considered an upper triangular matrix, else not
                if np.abs(A[i][j]) > tol:
                    return False
        return True
    
    def eigenDecompose(self, A):
        # A is a square, symmetric matrix

        n = len(A)
        X = np.copy(A)  # or X = my_copy(A), see below
        pq = np.identity(n)
        max_ct = 10000

        ct = 0
        while ct < max_ct:
            
            Q, R = self.QRDecompose(X)
            pq = np.matmul(pq, Q)  # accum Q
            X = np.matmul(R, Q)  # note order
            ct += 1

            if self.is_upper_tri(X, 1.0e-12) == True:
                break

        if ct == max_ct:
            print("WARN: no converge ")

        # eigenvalues are diag elements of X
        e_vals = np.zeros(n, dtype=np.float64)
        for i in range(n):
            e_vals[i] = X[i][i]

        # eigenvectors are columns of pq
        e_vecs = np.copy(pq)
        return (e_vals, e_vecs)
    
    
    def svd(self):

        A = self.A

        ATA = np.matmul(np.transpose(A), A)
        AAT = np.matmul(A, np.transpose(A))

        eigenvals1, eigenvecs1 = self.eigenDecompose(ATA)
        eigenvals2, eigenvecs2 = self.eigenDecompose(AAT)

        m,n = A.shape

        diagonal_matrix = np.zeros((m,n))
        z = min(m,n)

        for i in range(z):
            diagonal_matrix[i][i] = math.sqrt(eigenvals1[i])

        print(eigenvals1)
        print(eigenvecs1)
        print(diagonal_matrix)
        print(eigenvecs2)

        return eigenvecs2, diagonal_matrix, eigenvecs1
    
    def reduced_svd(self, k):

        U, Sigma, V = self.svd()
        U_reduced = U[:, 0:k]
        Sigma_reduced = Sigma[0:k, 0:k]
        V_reduced = V[:, 0:k]

        return U_reduced, Sigma_reduced, V_reduced      


SyntaxError: incomplete input (3311439168.py, line 95)

In [ ]:
def main():
  
  np.set_printoptions(suppress=True,
    precision=4, floatmode='fixed')

  A = np.array([[0.9, 0.8, 0.2],[0.3, 3, 0.4],[0.3, 1, 2]], dtype=np.float64)

  print("\nSource matrix: ")
  print(A)

  m = Matrix(A)
  
  print("\nPerforming SVD")
  U, Sigma, V = m.svd()
  A_prime = np.matmul(U, np.matmul(Sigma, np.transpose(V)))

  print("\nAfter SVD")
  print(A_prime)

  # U, Sigma, V = m.reduced_svd()
  # A_prime = np.matmul(U, np.matmul(Sigma, np.transpose(V)))
  # print("\nReduced SVD")
  # print(A_prime)

In [ ]:
if __name__ == "__main__":
  main()


Begin eigenvalues, eigenvectors from scratch 

Source matrix: 
[[0.9000 0.8000 0.2000]
 [0.3000 3.0000 0.4000]
 [0.3000 1.0000 2.0000]]

Performing SVD
[[ 0.1816 -0.0328 -0.9828]
 [ 0.9039  0.3991  0.1537]
 [ 0.3872 -0.9163  0.1021]]
[[3.5306 0.0000 0.0000]
 [0.0000 1.6639 0.0000]
 [0.0000 0.0000 0.7721]]
[[ 0.2730  0.0640 -0.9599]
 [ 0.8274  0.4934  0.2683]
 [ 0.4908 -0.8674  0.0818]]

After SVD
[[0.9000 0.8000 0.2000]
 [0.3000 3.0000 0.4000]
 [0.3000 1.0000 2.0000]]
