In [18]:
import numpy as np

In [19]:
def QRDecompose(A, standard=False):
    m, n = A.shape  
    Q = np.zeros((m, n))
    R = np.zeros((n, n))

    for j in range(n):
        v = A[:, j]
        for i in range(j):
            R[i, j] = np.dot(Q[:, i], A[:, j])
            v -= R[i, j] * Q[:, i]
        R[j, j] = np.linalg.norm(v)
        Q[:, j] = v / R[j, j]

    if standard:
        for i in range(n):
            if R[i, i] < 0.0:
                Q[:, i] *= -1
                R[i, :] *= -1

    return Q, R

In [20]:
def is_upper_tri(A, tol):
  n = len(A)
  for i in range(0,n):
    for j in range(0,i):
      # if the lower triangular entries fall below a threshold (tol), only then it is considered an upper triangular matrix, else not
      if np.abs(A[i][j]) > tol:
        return False
  return True

In [21]:
def eigenDecompose(A):
  # A is a square, symmetric matrix

  n = len(A)
  X = np.copy(A)  # or X = my_copy(A), see below
  pq = np.identity(n)
  max_ct = 10000

  ct = 0
  while ct < max_ct:
    
    Q, R = QRDecompose(X)
    pq = np.matmul(pq, Q)  # accum Q
    X = np.matmul(R, Q)  # note order
    ct += 1

    if is_upper_tri(X, 1.0e-8) == True:
      break

  if ct == max_ct:
    print("WARN: no converge ")

  # eigenvalues are diag elements of X
  e_vals = np.zeros(n, dtype=np.float64)
  for i in range(n):
    e_vals[i] = X[i][i]

  # eigenvectors are columns of pq
  e_vecs = np.copy(pq)
  return (e_vals, e_vecs)

In [22]:
def main():
  print("\nBegin eigenvalues, eigenvectors from scratch ")
  np.set_printoptions(suppress=True,
    precision=4, floatmode='fixed')

  A = np.array([[0.9, 0.5, 0.2],[0.5, 0.3, 0.4],[0.2, 0.4, 0.8]], dtype=np.float64)

  print("\nSource matrix: ")
  print(A)

  e_vals, e_vecs = eigenDecompose(A)
  print("\nEigenvalues from scratch: ")
  print(e_vals)
  print("\nEigenvectors (columns) from scratch: ")
  print(e_vecs)

  e_vals, e_vecs = np.linalg.eig(A)
  print("\neigenvalues from np.linalg: ")
  print(e_vals)
  print("\neigenvectors (columns) from np.linalg: ")
  print(e_vecs)

  print("\nEnd demo ")

In [23]:
if __name__ == "__main__":
  main()


Begin eigenvalues, eigenvectors from scratch 

Source matrix: 
[[0.9000 0.5000 0.2000]
 [0.5000 0.3000 0.4000]
 [0.2000 0.4000 0.8000]]

Eigenvalues from scratch: 
[ 1.4217  0.6439 -0.0655]

Eigenvectors (columns) from scratch: 
[[ 0.6815 -0.6223 -0.3850]
 [ 0.4958  0.0057  0.8684]
 [ 0.5383  0.7828 -0.3124]]

eigenvalues from np.linalg: 
[ 1.4217  0.6439 -0.0655]

eigenvectors (columns) from np.linalg: 
[[-0.6815 -0.6223  0.3850]
 [-0.4958  0.0057 -0.8684]
 [-0.5383  0.7828  0.3124]]

End demo 
